pipeline {
  agent any
  environment {
    PYTHONUNBUFFERED = 'TRUE'
    SAGEMAKER_PROJECT_NAME_ID = """${sh(
      returnStdout: true,
      script: 'echo "${SAGEMAKER_PROJECT_NAME}-${SAGEMAKER_PROJECT_ID}"'
      ).trim()}"""
  }
  stages {
    stage('Build and Install') {
      steps {
        //sh '''pip3 install --upgrade --force-reinstall --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID . "awscli>1.20.30"'''
        sh '''
        echo "AWS version is $(aws --version)  "
        echo "Env variables are location -- is $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID"
        echo "Env variable HOME is $HOME"
        echo "Env Variable SAGEMAKER_PIPELINE_ROLE_ARN is $SAGEMAKER_PIPELINE_ROLE_ARN"
        echo "Env variable ARTIFACT_BUCKET is $ARTIFACT_BUCKET"
        '''
      }
    }
    stage('Update and Run Sagemaker Pipeline') {
      steps {
        withAWS(credentials:"${AWS_CREDENTIAL}",region:"${AWS_REGION}") {
          sh '''
          export PATH="$HOME/.jenkins/workspace/$SAGEMAKER_PROJECT_NAME_ID/bin:$PATH"
          export PYTHONPATH="$HOME/.jenkins/workspace/$SAGEMAKER_PROJECT_NAME_ID:$PYTHONPATH"
          run-pipeline --module-name pipelines.abalone.pipeline \
          --role-arn ${SAGEMAKER_PIPELINE_ROLE_ARN} \
          --tags "[{\\"Key\\":\\"sagemaker:project-name\\", \\"Value\\":\\"${SAGEMAKER_PROJECT_NAME}\\"}, {\\"Key\\":\\"sagemaker:project-id\\", \\"Value\\":\\"${SAGEMAKER_PROJECT_ID}\\"}]" \
          --kwargs "{\\"region\\":\\"${AWS_REGION}\\",\\"sagemaker_project_arn\\":\\"${SAGEMAKER_PROJECT_ARN}\\",\\"role\\":\\"${SAGEMAKER_PIPELINE_ROLE_ARN}\\",\\"default_bucket\\":\\"${ARTIFACT_BUCKET}\\",\\"pipeline_name\\":\\"${SAGEMAKER_PROJECT_NAME_ID}\\",\\"model_package_group_name\\":\\"${SAGEMAKER_PROJECT_NAME_ID}\\",\\"base_job_prefix\\":\\"${SAGEMAKER_PROJECT_NAME_ID}\\"}"
          '''

          echo "Create/Update of the SageMaker Pipeline and execution completed."
        }
      }
    }
  }
}


